name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        options: --name my-mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: aliceolsson96
          MONGO_INITDB_ROOT_PASSWORD: Gullberna1


    strategy:
      matrix:
        node-version: [16.x, 18.x]
        mongodb-version: ['4.2', '4.4', '5.0']

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set NODE_ENV to 'test'
      run: echo "NODE_ENV=test" >> $GITHUB_ENV
  
    - name: Change directory and list contents
      run: |
        cd train-controller-1.1/backend
        ls
    - name: Install dependencies
      working-directory: train-controller-1.1/backend # Set the working directory here
      run: npm install
    - name: Install Mocha globally
      run: npm install -g mocha # You can install Mocha globally if needed
    - name: Run tests
      working-directory: train-controller-1.1/backend/test/unittest-mocha-istanbul/test # Set the working directory here
      run: npm test

