name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        mongodb-version: ['4.2', '4.4', '5.0']

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up environment variables
      run: |
        echo "MONGO_URL=mongodb://localhost:27017/test" >> $GITHUB_ENV
        echo "MONGO_USERNAME=aliceolsson96" >> $GITHUB_ENV
        echo "MONGO_PASSWORD=Gullberna1" >> $GITHUB_ENV

    - name: Change directory and list contents
      run: |
        cd train-controller-1.1/backend
        ls
    - name: Install dependencies
      working-directory: train-controller-1.1/backend # Set the working directory here
      run: npm install
    - name: Install Mocha globally
      run: npm install -g mocha # You can install Mocha globally if needed
    - name: Run tests
      working-directory: train-controller-1.1/backend/test/unittest-mocha-istanbul/test # Set the working directory here
      run: npm test

