name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]
        mongodb-version: ['4.2', '4.4', '5.0']

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Change directory and list contents
      run: |
        cd train-controller-1.1/backend
        ls
    - name: Install dependencies
      working-directory: train-controller-1.1/backend/test/unittest-mocha-istanbul # Set the working directory here
      run: |
        npm install
        npm install -g mocha
    - name: Run tests
      working-directory: train-controller-1.1/backend/test/unittest-mocha-istanbul/test # Set the working directory here
      run: npm test

