name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        mongodb-version: ['4.2', '4.4', '5.0']

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Change directory and list contents
      run: |
        cd train-controller-1.1/backend
        ls

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install dependencies
      working-directory: train-controller-1.1/backend
      run: npm install

    - name: Install Sinon
      working-directory: train-controller-1.1/backend
      run: npm install sinon --save-dev

    - name: Install Mocha globally
      run: npm install -g mocha

    - name: Run tests
      working-directory: train-controller-1.1/backend/test/unittest-mocha-istanbul/test
      run: npm test

